### PR TITLE
Issue-3 : Added required files to avoid the libs issue

### PR DESCRIPTION
**Pull request by sumangala028**
I have added the following files to the [libs_issue](https://github.com/JudeNiroshan/openmrs-owa-built-in-reports/tree/libs_issue) branch to avoid the dependency problem. 

1.  jquery.tagsinput
2.  jquery/dist
3.  bootstrap/dist

Issue : #3

### CODE REVIEW

**Comment by ridmal** [comment]
My opinion is that normally we don't want to add libs manually to the code base we need to add lib folder inside the gitignore file. Because passing libs through the version-control is not the best practice. That is why we use bower for installing the UI libraries to the code base.So i think we need to consider about that. @JudeNiroshan What do you think ?

**Comment by JudeNiroshan** [comment]
@ridmal  yes, I agree with it. That's why i have ignored the libs folder completely. I think the best fix for this issue is modify the webpack and bower configuration files to refer to the dependencies. But for the moment of creating your proposals and other work, you may proceed with it temporary fix.

**Comment by ridmal** [comment]
I solve the issue 1 and I think it will solve this issue too. Can you review that [PR](https://github.com/JudeNiroshan/openmrs-owa-built-in-reports/pull/5) for issue 1?

**Comment by sumangala028** [comment]
Yah, For temporally we can attach this required files to only libs_issue branch. Then we can fix in in the master branch.

**Comment by JudeNiroshan** [comment]
With the fix from @ridmal , I think we can avoid placing the dependencies in our source code. It is actually against the convention of using dependencies in a project. However, I appreciate your effort 👍

**Pull request closed without merging**
