### PR TITLE
Issue-9 Added location swticher functionalities and Added a fix on fetching active location from Session

### PR DESCRIPTION
**Pull request by sumangala028**
I have fixed the location switcher issues. I have tested the implementation locally, and it worked for me without any issues.

Please find the fixes below,

1. Active current location will be fetched from the "appui/session" end point.
2. Location changes will be sent to the "appui/session" to replace the current active location information.

Issue : #9

### CODE REVIEW

**Comment by sumangala028** [comment]
@JudeNiroshan I have created new PR,but since I couldn't get the updates from newly updated eslint? Could you please help me to figure it out?

**Comment by JudeNiroshan** [comment]
@sumangala028  could you please correct the indentations which reported in Codacy review?

**Comment by sumangala028** [comment]
@JudeNiroshan  Sorry for that problem, I have fixed it now

**Comment by JudeNiroshan** [comment]
Good job!

**Pull request merged**
